### PR TITLE
Refactor: Use Chat Completions API

### LINKED ISSUE #52: Default model text-davinci-003 deprecated
Error: {"message":"The model `text-davinci-003` has been deprecated, learn more here: https://platform.openai.com/docs/deprecations","type":"invalid_request_error","param":null,"code":"model_not_found"}

The new models should be added to the ai model menu.

### PR DESCRIPTION
**Pull request by arindamlahiri**
Fixes #52 

### Changes
- Refactored the code to use the [Chat Completions API](https://platform.openai.com/docs/guides/text-generation/chat-completions-api)
   - Updated openai package to latest version - v4
- Default model - `gpt-3.5-turbo`
- User can switch to `gpt-4`
- Removed `top_p` param as OpenAI suggests to only alter either `temperature` or `top_p`. Keeping both made `gpt-3.5-turbo` not follow the constraints

```
# with top_p
> ai ask "biggest country in the world?"
> Command is `The biggest country in the world by land area is Russia.`
```
```
# without top_p
> ai ask "biggest country in the world?"
> Sorry, Can't answer that.
```
/claim #52

### CODE REVIEW

**Comment by abhagsain** [comment]
Thanks for the PR, but we want to refactor it to GPT3.5 (Chat Model) so users can switch to GPT4 if they want to.

**Comment by arindamlahiri** [comment]
Got it. Will refactor it to use the new Chat completions API

**Comment by arindamlahiri** [comment]
Updated the PR description to reflect the new changes

**Comment by arindamlahiri** [comment]
@abhagsain can you please check this? I have refactored the code to use the new Chat Completions API

**Comment by abhagsain** [comment]
> @abhagsain can you please check this? I have refactored the code to use the new Chat Completions API

Hi, @arindamlahiri 
I just checked, and it's not working as expected.
The issue is for an existing user who already has AI CLI installed. It will pick the `text-davinci-003` model. (because it's saved in the `config.json`). 
Users can switch to the turbo model manually, but it would be a good UX if we had checks in place if the user is using the deprecated model and replacing it with the new one. (Let's fallback to the cheapest one)
Also, please change the README.md as well.

Thanks

**Comment by arindamlahiri** [comment]
Hi @abhagsain 
The required changes are done. Added a fallback to `gpt-3.5-turbo` in case the saved model is not in our defined list.

In the README, I have updated the pricing section and references to the default model.
Let me know if you want any other changes in the README.

**Review by abhagsain — APPROVED** [review]
✅ LGTM

Thanks @arindamlahiri

**Pull request merged**
